name: ppinsight
channels:
  - conda-forge
  - bioconda
  - defaults
  - pip
dependencies:
  - python=3.11
  - numpy>=1.24
  - pandas
  - matplotlib>=3.6
  - seaborn>=0.12
  - networkx
  - requests
  - biopython
  - pytest
  - pytest-cov
  - ruff
  - mpi4py
  - zlib
  - haddock_biobb==2025.5
  - c-compiler
  - cxx-compiler
  - fortran-compiler
  - pip
  - pip:
    - lightdock
    - pyrosetta-installer
    - git+https://github.com/nrontsis/DockQ.git@update-to-numpy>2